ARG DEBIAN_RELEASE
FROM astercti-build-debian-$DEBIAN_RELEASE
USER 0

RUN apt-get update -yq \
    && apt-get install -yq --no-install-recommends \
        binutils-mingw-w64-i686 \
        g++-mingw-w64-i686 \
        nsis \
        unzip \
    && apt-get clean \
    &&  rm -rf \
        /var/lib/apt/lists/* \
        /var/tmp/* \
        /tmp/*

# Obtaining wxMSW

ARG WXVER=3.2.8
RUN wget -q -O /build/wxWidgets-$WXVER.tar.bz2 https://github.com/wxWidgets/wxWidgets/releases/download/v$WXVER/wxWidgets-$WXVER.tar.bz2
RUN tar xf /build/wxWidgets-$WXVER.tar.bz2 -C /build/
RUN cd /build/wxWidgets-$WXVER \
    && ./configure \
        --disable-shared \
        --enable-unicode \
        --prefix=/usr/local/i686-mingw32-g++ \
        --host=i686-w64-mingw32 \
        --build=x86_64-linux \
        CFLAGS='-I/usr/i686-w64-mingw32/include' \
    && make -j $(grep -c ^processor /proc/cpuinfo)
RUN cd /build/wxWidgets-$WXVER \
    && mkdir -p /usr/local/i686-mingw32-g++/bin \
    && make install --  \
    && make clean \
    && cd /build \
    && rm -rf /build/wxWidgets-$WXVER*
RUN ln -s /usr/local/i686-mingw32-g++ /usr/local/libwxmsw3.2

# Obtaining jsoncpp for Windows

ARG JSONCPPVER=1.9.6
RUN wget -q -O /build/jsoncpp.tar.gz https://github.com/open-source-parsers/jsoncpp/archive/$JSONCPPVER.tar.gz \
    && tar xf /build/jsoncpp.tar.gz -C /build \
    && mv /build/jsoncpp-$JSONCPPVER /build/jsoncpp \
    && cd /build/jsoncpp \
    && python3 amalgamate.py \
    && rm -rf /build/jsoncpp.tar.gz

# Obtaining libcurl for Windows
RUN wget -O /build/curl.zip 'https://curl.se/windows/latest.cgi?p=win32-mingw.zip' \
    && unzip -d /build /build/curl.zip \
    && mv /build/curl-* /build/curl \
    && chmod -R 755 /build/curl \
    && cp -r /build/curl/include/curl /usr/i686-w64-mingw32/include/ \
    && ln -s /build/curl/bin/libcurl.dll /build/astercti/ \
    && rm /build/curl.zip

# A hack because mingw doesn' try *.dll.a lib extensions:
RUN for lib in $(ls /usr/local/i686-mingw32-g++/lib/*.dll.a | sed 's/\.dll\.a$//'); do ln -s $lib.dll.a $lib.a ; done

RUN ln -s /usr/local/i686-mingw32-g++/lib/wx/include/i686-w64-mingw32-msw-unicode-3.2/wx/setup.h /usr/local/i686-mingw32-g++/include/wx-3.2/wx/setup.h

ARG UID=1000
USER $UID

# vi: ft=dockerfile:
